# Generated by Django 4.1.3 on 2022-11-25 16:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('designation', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=800)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=800)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Remodeling', 'Remodeling'), ('Construction', 'Construction'), ('Repairs', 'Repairs'), ('Design', 'Design')], default='Remodeling', max_length=250)),
                ('image', models.ImageField(upload_to='projects')),
                ('title', models.CharField(max_length=800)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('sub_title', models.CharField(max_length=800)),
                ('slide', models.ImageField(upload_to='slider_image')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=800)),
                ('designations', models.CharField(max_length=800)),
                ('message', models.CharField(max_length=800)),
            ],
        ),
    ]
