# Generated by Django 4.1.3 on 2022-11-28 18:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('sub_title', models.CharField(max_length=800)),
                ('establish_year', models.CharField(max_length=100)),
                ('details', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='about')),
                ('video_embed', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to='construction')),
                ('details', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Modisit', 'Modisit'), ('Praesenti', 'Praesenti'), ('Explica', 'Explica'), ('Nostrum', 'Nostrum')], max_length=100)),
                ('title', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to='feature')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ourTeam')),
                ('name', models.CharField(max_length=800)),
                ('designation', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=800)),
                ('twitter_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('icon', models.ImageField(upload_to='services')),
                ('details', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
